name: jagatfilm
description: JagatFilm - Streaming Drama Indonesia
publish_to: 'none'
version: 2.0.0+11

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 1.2.1
  cached_network_image: 3.3.1
  video_player: 2.9.2
  chewie: 1.8.5
  shared_preferences: 2.2.3
  provider: 6.1.2
  shimmer: 3.0.0
  flutter_staggered_grid_view: 0.7.0
  url_launcher: 6.2.6
  package_info_plus: 8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2

flutter:
  uses-material-design: true
